export default {
    BREWERIES_QUERY_SUCCESS: 'BREWERIES_QUERY_SUCCESS',
    BREWERIES_NEW_SUCCESS: 'BREWERIES_NEW_SUCCESS',
    BREWERIES_UPDATE_SUCCESS: 'BREWERIES_UPDATE_SUCCESS',
    BREWERIES_REMOVE_SUCCESS: 'BREWERIES_REMOVE_SUCCESS',
    BREWERIES_CHANGE_UI: 'BREWERIES_CHANGE_UI',

    IMAGE_UPLOADED: 'IMAGE_UPLOADED',
    BEGIN_GRAPHQL_CALL: 'BEGIN_GRAPHQL_CALL',
    GRAPHQL_ERROR: 'GRAPHQL_ERROR'
};